### PR TITLE
Add aim mode

### PR DESCRIPTION
**Pull request by FlattestGuitar**
:cl: Flatty
add: Pointing at someone with a gun in hand will make you target them threateningly!
/:cl:

### CODE REVIEW

**Comment by FlattestGuitar** [comment]
The `X points at Y` bits don't show anymore, but I can't be bothered

**Comment by msgerbs** [comment]
> The `X points at Y` bits don't show anymore, but I can't be bothered

What do you mean by this?

**Comment by FlattestGuitar** [comment]
In chat in that gif I posted you can see `Byron Hunt points at Unknown`. 

That is old behavior, as that line does not print anymore in the current version of the code, but I could not be bothered to rerecord the gif.

**Comment by msgerbs** [comment]
Oh OK. So this is good?

**Pull request merged**
