### PR TITLE
Removes /VG/ Laughing Emoji Mask and Cat Ears.

### PR DESCRIPTION
**Pull request by ShibberinoShipperino**
/TG/ Map had to be updated to remove the Emoji Mask Spawn.

Removes both the Laughing Emoji Mask and the Cat Ears.

Compiled with no issues.

### CODE REVIEW

**Comment by msgerbs** [comment]
Ignoring the erroneous CI failure, do we really need to remove them? Just remove them from the map. We don't need to remove everything we're not using.

**Comment by msgerbs** [comment]
Also you're probably going to have to redo this once the maps get fixed to stop failing CI checks... Sorry not sorry.

**Comment by MrFroztee** [comment]
I'm totally for removing shitty meme items. Eventually, a self-defined codebase won't have any traces of the code it was derived from, and anywhere is a good start.

**Comment by msgerbs** [comment]
These items need to be removed from other maps as well.

`maps/metaclub.dmm:8619:error: undefined type: /obj/item/clothing/mask/joy
maps/metaclub.dmm:8619:error: unknown type
maps/defficiency.dmm:8010:error: undefined type: /obj/item/clothing/mask/joy
maps/defficiency.dmm:8010:error: unknown type
maps/packedstation.dmm:4401:error: undefined type: /obj/item/clothing/mask/joy
maps/packedstation.dmm:4401:error: unknown type`

**Comment by ShibberinoShipperino** [comment]
Closing for now as we can just avoid mapping them in. It would be a good idea to go through and remove all unwanted clothing in a big PR instead. Recommend making a list.

**Pull request closed without merging**
